#!/bin/bash
#
# Control plugwise modules
#
# http://www.maartendamen.com/2010/08/plugwise-unleashed-document-released/
#
# Copyright (C) 2012 Jamie Lentin <jm@lentin.co.uk>
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.

[ "$1" = "-v" ] && { verbose=1; shift; }

unset LANG      # A UTF-8 LANG will cause bashes read to read multibyte characters
export LC_CTYPE=C
export LC_ALL=C # Force a non UTF-8 Lang to load (prevent multibyte characters)
IFS=''          # Stop read treating " " as a field separator

CRC_TBL=(0x0000 0x1021 0x2042 0x3063 0x4084 0x50a5 0x60c6 0x70e7
         0x8108 0x9129 0xa14a 0xb16b 0xc18c 0xd1ad 0xe1ce 0xf1ef
         0x1231 0x0210 0x3273 0x2252 0x52b5 0x4294 0x72f7 0x62d6
         0x9339 0x8318 0xb37b 0xa35a 0xd3bd 0xc39c 0xf3ff 0xe3de
         0x2462 0x3443 0x0420 0x1401 0x64e6 0x74c7 0x44a4 0x5485
         0xa56a 0xb54b 0x8528 0x9509 0xe5ee 0xf5cf 0xc5ac 0xd58d
         0x3653 0x2672 0x1611 0x0630 0x76d7 0x66f6 0x5695 0x46b4
         0xb75b 0xa77a 0x9719 0x8738 0xf7df 0xe7fe 0xd79d 0xc7bc
         0x48c4 0x58e5 0x6886 0x78a7 0x0840 0x1861 0x2802 0x3823
         0xc9cc 0xd9ed 0xe98e 0xf9af 0x8948 0x9969 0xa90a 0xb92b
         0x5af5 0x4ad4 0x7ab7 0x6a96 0x1a71 0x0a50 0x3a33 0x2a12
         0xdbfd 0xcbdc 0xfbbf 0xeb9e 0x9b79 0x8b58 0xbb3b 0xab1a
         0x6ca6 0x7c87 0x4ce4 0x5cc5 0x2c22 0x3c03 0x0c60 0x1c41
         0xedae 0xfd8f 0xcdec 0xddcd 0xad2a 0xbd0b 0x8d68 0x9d49
         0x7e97 0x6eb6 0x5ed5 0x4ef4 0x3e13 0x2e32 0x1e51 0x0e70
         0xff9f 0xefbe 0xdfdd 0xcffc 0xbf1b 0xaf3a 0x9f59 0x8f78
         0x9188 0x81a9 0xb1ca 0xa1eb 0xd10c 0xc12d 0xf14e 0xe16f
         0x1080 0x00a1 0x30c2 0x20e3 0x5004 0x4025 0x7046 0x6067
         0x83b9 0x9398 0xa3fb 0xb3da 0xc33d 0xd31c 0xe37f 0xf35e
         0x02b1 0x1290 0x22f3 0x32d2 0x4235 0x5214 0x6277 0x7256
         0xb5ea 0xa5cb 0x95a8 0x8589 0xf56e 0xe54f 0xd52c 0xc50d
         0x34e2 0x24c3 0x14a0 0x0481 0x7466 0x6447 0x5424 0x4405
         0xa7db 0xb7fa 0x8799 0x97b8 0xe75f 0xf77e 0xc71d 0xd73c
         0x26d3 0x36f2 0x0691 0x16b0 0x6657 0x7676 0x4615 0x5634
         0xd94c 0xc96d 0xf90e 0xe92f 0x99c8 0x89e9 0xb98a 0xa9ab
         0x5844 0x4865 0x7806 0x6827 0x18c0 0x08e1 0x3882 0x28a3
         0xcb7d 0xdb5c 0xeb3f 0xfb1e 0x8bf9 0x9bd8 0xabbb 0xbb9a
         0x4a75 0x5a54 0x6a37 0x7a16 0x0af1 0x1ad0 0x2ab3 0x3a92
         0xfd2e 0xed0f 0xdd6c 0xcd4d 0xbdaa 0xad8b 0x9de8 0x8dc9
         0x7c26 0x6c07 0x5c64 0x4c45 0x3ca2 0x2c83 0x1ce0 0x0cc1
         0xef1f 0xff3e 0xcf5d 0xdf7c 0xaf9b 0xbfba 0x8fd9 0x9ff8
         0x6e17 0x7e36 0x4e55 0x5e74 0x2e93 0x3eb2 0x0ed1 0x1ef0)

function crc() {
    i=0;
    CRC=0;
    while [ $i -lt ${#1} ]; do
        CHR="$(printf '%d' "'${1:$i:1}")"
        CRC=$(( ${CRC_TBL[$CHR ^ ($CRC >> 8 & 0xFFFF)]} ^ ($CRC << 8 & 0xFFFF) ))
        i=$(( i+1 ))
    done
    printf '%X' $CRC
}

function send_command() {
    (
        [ "$1" = "on"    ] && DATA="0017${CIRCLE}01"
        [ "$1" = "off"   ] && DATA="0017${CIRCLE}00"
        [ "$1" = "usage" ] && DATA="0012${CIRCLE}"
        [ "$1" = "info" ] && DATA="0023${CIRCLE}"
        [ "$1" = "calibration" ] && DATA="0026${CIRCLE}"
        [ -n "$DATA" ] || {
            echo "Unknown command" 1>&2
            exit 1
        }
        echo Sending $DATA 1>&2

        # Wait for main thread to be ready before issuing command
        sleep 0.1s
        printf '\x0d\x0a\x05\x05\x03\x03%s%s\x0d\x0a' $DATA $(crc $DATA)
    ) >$PORT &
}

function usage() {
    echo Usage: "$0 (circle) (on|off|usage|info)" 1>&2
    exit 1
}

# Set up serial port
PORT=/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A2003FCu-if00-port0
stty --file $PORT cs8 -cstopb -crtscts -ixon -ixoff -ignpar cread 115200

# Choose circle
CIRCLE=$1
[ "${CIRCLE:0:4}" == "000D" ] || usage

# Choose command
COMMAND=$2
[ -n "$COMMAND" ] || usage

(
    for attempt in 1 2 3; do
        send_command $COMMAND

        SEQ=""
        while read -r -t 1 -s raw; do
            # Check for header
            [ "${raw:0:4}" = "$(echo -ne "\x05\x05\x03\x03")" ] || {
                # echo "Missing header" 1>&2
                continue
            }
            echo "Received $raw" 1>&2

            # Check CRC of incoming packet
            [ "${raw:${#raw} - 5:4}" = "$(crc ${raw:4:${#raw} - 9})" ] || {
                echo "CRC mismatch" 1>&2
                # continue
            }

            # Confirmation packet from stick: 0000 001A 00C1 A6CB
            [ -z "$SEQ" -a "${raw:4:4}" = "0000" -a "${raw:12:4}" = "00C1" ] && {
                SEQ="${raw:8:4}"
                continue
            }

            [ -z "$SEQ" ] && {
                echo "Sequence not set" 1>&2
                continue
            }

            # Anything after this should have our sequence number
            [ "${raw:8:4}" = "$SEQ" ] || {
                echo "Sequence mismatch ${raw:8:4} $SEQ" 1>&2
                # continue
            }

            # Power command response: 0000 0017 00D8 000D6F00007698F1 1032
            [ "${raw:4:4}" = "0000" -a "${raw:16:16}" = "$CIRCLE" ] && {
                [ "${raw:12:4}" = "00D6" ] && STATUS="on"
                [ "${raw:12:4}" = "00D8" ] && STATUS="on"
                [ "${raw:12:4}" = "00DE" ] && STATUS="off"
                [ -n "$STATUS" ] || {
                    echo "Unknown status ${raw:12:4}" 1>&2
                    exit 1
                }

                [ "$STATUS" = "$2" ] && {
                    echo "Power: ${STATUS}"
                    exit 0
                }
            }

            # Current power usage: 000B 0055 000044BE FFFE 5312 000B 0893
            [ "${raw:4:4}" = "0013" -a "${raw:12:16}" = "$CIRCLE" ] && {
                printf "Usage: %d pulses/sec %d pulses/8secs\n" 0x${raw:28:4} 0x${raw:32:4}
                exit 0
            }

            # Device information: 00 01 A408 0006A170 01856539090093034AA66127025A42
            [ "${raw:4:4}" = "0024" -a "${raw:12:16}" = "$CIRCLE" ] && {
                printf "Year: %d\nMonth: %d\nMinutes: %d\n" 0x${raw:28:2} 0x${raw:30:2} 0x${raw:32:4}
                echo "Log address: ${raw:36:8}"
                echo "Power state: ${raw:44:2}"
                echo "Power freq: ${raw:46:2}"
                echo "H/W version: ${raw:48:12}"
                echo "F/W version: ${raw:60:8}"
                exit 0
            }

            # Calibration information: 3F7FEC9E B651A72A BE7E1A15 00000000
            [ "${raw:4:4}" = "0027" -a "${raw:12:16}" = "$CIRCLE" ] && {
                echo "gaina: ${raw:28:8}"
                echo "gainb: ${raw:36:8}"
                echo "offtot: ${raw:44:8}"
                echo "offruis: ${raw:52:8}"
                exit 0
            }
        done
    done
    echo "All attempts failed!" 1>&2
    exit 1
) <$PORT
